import type { Bank, Question } from './schema'

export function renderReview(bank: Bank): string {
  const scaleById = new Map(bank.scales.map(s => [s.id, s]))
  const lines: string[] = [
    `# Question Bank Review — v${bank.meta.bankVersion}`,
    '',
    `_Active + draft questions, grouped by category. Generated by \`npm run bank:review\` — do not edit by hand._`,
    '',
  ]
  for (const cat of bank.categories) {
    const qs = bank.questions.filter(q => q.category === cat.id && q.status !== 'retired')
    if (qs.length === 0) continue
    lines.push(`## ${cat.name} (\`${cat.id}\`, weight ${cat.weight})`, '')
    const inputsUsed = [...new Set(qs.map(q => q.input))]
    for (const id of inputsUsed) {
      const s = scaleById.get(id)
      if (s) lines.push(`> **${id}**: ${s.anchors.map(a => `${a.value} = ${a.label}`).join(' · ')}`)
    }
    lines.push('')
    const fmt = (q: Question) => {
      const prefix = q.status === 'draft' ? '🚧 DRAFT — ' : ''
      if (q.slots) {
        const { what, problem } = q.slots
        return `- ${prefix}${what} — ${problem}` +
          `\n  _${q.text}_` +
          `  \n  \`${q.qid}\` v${q.v} · ${q.tier} · ${q.input}${q.flags.length ? ' · ' + q.flags.join(', ') : ''}`
      }
      return `- ${prefix}${q.text}` +
        `  \n  \`${q.qid}\` v${q.v} · ${q.tier} · ${q.input}${q.flags.length ? ' · ' + q.flags.join(', ') : ''}`
    }
    for (const q of qs.filter(q => q.tier === 'core')) lines.push(fmt(q))
    for (const q of qs.filter(q => q.tier === 'drilldown')) lines.push(fmt(q))
    lines.push('')
  }
  return lines.join('\n')
}
